//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Delivery_Check.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("128, 255, 128")]
        public global::System.Drawing.Color succeeded {
            get {
                return ((global::System.Drawing.Color)(this["succeeded"]));
            }
            set {
                this["succeeded"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 90, 90")]
        public global::System.Drawing.Color latecomer {
            get {
                return ((global::System.Drawing.Color)(this["latecomer"]));
            }
            set {
                this["latecomer"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8BR9uhsnRV+xK2IeQgx37OFEBnteuEU/Pn44JppS/A0jaNCfGUBqSc16DDXpxfoGuWOS7TnIC+Dwo1Bzw" +
            "EC6P27EqnrwIXePvKFfhNg3usmakvT4YvY0oEYi2tDLon1vgJfhT6Fy0RE2uDgNPRhVOuMaKasuAhKdq" +
            "P2Z7cAWRQ43Bq3N+S2GV/EwulzoXAJsfiCjZ7A9u3XDIAteAIhjWQ==")]
        public string whatIsIt {
            get {
                return ((string)(this["whatIsIt"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("zIiinkA3vgGy4LgF8bso8ALoWk0gZiJuP0BAshFiz4cGHJenc80fjl9JEDAqwjaNUFlvd81UhozgHQ2QL" +
            "pmmGcIGfEEYTGUDEpgN")]
        public string toIsIt {
            get {
                return ((string)(this["toIsIt"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"zIiinkA3vgGy4LgF8bso8ALoWk0gZiJuP0BAshFiz4cGHJenc80fjl9JEDAqwjaNUFlvd81UhozgHQ2QLpmmGcIGfEEYTGUDEpgNTbriBASr9Fx1l81FrTzYNe8IkRrrHjjRKOZulQU0b1Lqqf9iVdavT9WEGxrRGlS755m1fpgr6aBa9X1pajXTJaeJfrs30fZzGV+JZsmL5ypoXzxfaaYofkDAxdykBR8IUK7zMLbkWp57h8ONCd/B4WcwMCg96NSPB6J1AB4xq7OdxwwE8A7sPj+26cvEc3xLv4462llMmPpjuBIy3iNUXw==")]
        public string encryptUser {
            get {
                return ((string)(this["encryptUser"]));
            }
            set {
                this["encryptUser"] = value;
            }
        }
    }
}
